package:
  name: carme
  version: v

source:
  git_rev:
  git_url: https://github.com/carmelabs/carme.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
  license: MIT
  license_file:
